rsvplist.settings:
  type: config_object
  label: 'RSVP List Content Type Settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Allowed content types where the RSVP form can be displayed'
      sequence:
        - type: string
          label: 'Content type'
